{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: radix-allow-namespace
spec:
  podSelector: {}
  policyTypes: ["Egress","Ingress"]
  ingress:
    - from:
      - podSelector: {}   # same namespace
  egress:
    - to:
      - podSelector: {}   # same namespace
{{- end }}
