{{- if .Values.mvp.instantPreview.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: radix-observer
  labels: { app.kubernetes.io/name: radix-core }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radix-observer-readonly
rules:
  - apiGroups: [""]
    resources: ["pods","nodes","events"]
    verbs: ["get","list","watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: radix-observer-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: radix-observer-readonly
subjects:
- kind: ServiceAccount
  name: radix-observer
  namespace: {{ .Release.Namespace }}
{{- end }}
